version: 2

# emtpy test, to keep circle ci silent. Please replace with a normal trunk
# yml after 6.6 RELEASE

references:

  dummy_item: &dummy_item
    run:
      name: Return true to keep circle ci happy
      command: /bin/true

jobs:

  dummy_job:
    docker:
      - image: busybox:latest
    steps:
      - *dummy_item

workflows:

  version: 2
  test-matrix:
    jobs:
      - dummy_job
